print("Atome = noyau constitué de\n- nucléons :\n   - protons de charge e+\n   - neutrons de charge nulle\n- d'electrons de charge \nnégative -e")
print("La lettre e désigne la \ncharge électrique élémentaire. \nElle vaut e = 1,60×10-19 C")
print("Dans un atome, il y a autant \nde protons que d-électrons. \nLa charge totale est nulle : \nun atome est électriquement \nneutre.") 
print("Un ion est un atome (ou un \ngroupement d-atomes) ayant \ngagné ou perdu des électrons.")
print("Ordre de grandeur de la taille\nd-un - noyau atomique : \n~10−10 m (Angström)\n- d-un atome : ~10−15 m \n(femtomètre)")
print("A : nombre de nucléons \nZ : numéro atomique (protons) \nX : symbole")
print("Dans l-état fondamental \n(état de plus basse énergie), \nles électrons occupent les \ncouches et sous-couches dans \nl-ordre suivant :\n 1s → 2s → 2p → 3s → 3p\nExemple : pour le carbone C il \ny a 6 électrons à placer. Sa \nconfiguration électronique est\n1s2 2s2 2p2")